// Generated by CoffeeScript 1.10.0

/*
 * Copyright (c) 2016 Yonatan Romero
 * Licensed under the GPLv3 license.
 */

(function() {
  (function($) {
    $.jquery.heremap = function(options) {
      options = $.extend({}, $.jquery.heremap.options, options);
      return 'jquery.heremap' + options.punctuation;
    };
    return $.jquery.heremap.options = {
      app_id: '',
      app_code: '',
      punctuation: '.',
      zoom: 10,
      center: {
        lng: 0,
        lat: 0
      }
    };
  })(jQuery);

}).call(this);
